#!/usr/bin/env php
<?php

require_once $argv[1];

$staticMapFile = str_replace(
    'autoload.php',
    'composer/autoload_static.php',
    $argv[1]
);

$fp = fopen($staticMapFile, 'r');

$staticClass = $buffer = '';
$i = 0;
while (!$staticClass) {
    if (feof($fp)) break;

    $buffer = fread($fp, 150);
    $tokens = token_get_all($buffer);

    if (strpos($buffer, '{') === false) continue;

    for (; $i < count($tokens); $i++) {
        if ($tokens[$i][0] === T_CLASS) {
            for ($j = $i + 1; $j < count($tokens); $j++) {
                if ($tokens[$j] === '{') {
                    $staticClass = $tokens[$i + 2][1];
                }
            }
        }
    }
}

$staticClass = '\\Composer\\Autoload\\' . $staticClass;
$classMap = $staticClass::$classMap;

$classes = [];
foreach ($classMap as $key => $value) {

    $fqnClassName = ltrim($key, '\\');
    $parts = explode('\\', $fqnClassName);
    $className = array_pop($parts);

    $classes[$className][] = $key;
}

file_put_contents($argv[2].'/vendor.php', '<?php return '. var_export($classes, true). ';');